apiVersion: docs.opentelekomcloud.com/v1alpha1
kind: Space
metadata:
  labels:
    app.kubernetes.io/name: docurator
    app.kubernetes.io/managed-by: kustomize
  name: change-guides
spec:
  name: change-guides
  giteaSecretRef:
    name: gitea-spaces
